// Code generated placeholder by lin. Replace with `gorm gen` output via:
//
//	make gen-model
//
//go:generate go run {{.Module}}/cmd/gen-gorm-model
package model

import "time"

// {{.Resource | Pascal}}M is the database mapping model for {{.Resource | Pascal}} (placeholder).
//
// ⚠️ This file is a placeholder generated by lin. It exists only to allow the
// project to compile immediately after `linctl add`. Recommended workflow:
//  1. Create the corresponding database table (manage DDL manually).
//  2. Run `make gen-model` to invoke cmd/gen-gorm-model and auto-generate the
//     real model from the database schema.
//  3. The placeholder will be overwritten; commit the gorm gen output.
type {{.Resource | Pascal}}M struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement" json:"id"`
	{{.Resource | Pascal}}ID string    `gorm:"column:{{.Resource | Snake}}_id;uniqueIndex;type:varchar(35);not null" json:"{{.Resource | LowerCamel}}ID"`
	CreatedAt time.Time `gorm:"column:created_at" json:"createdAt"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updatedAt"`
}

// TableName specifies the database table name for {{.Resource | Pascal}}M.
func ({{.Resource | Pascal}}M) TableName() string {
	return "{{.Resource | Snake | Plural}}"
}
