# {{.ProjectName | Title}}

> Generated by [lin](https://github.com/clin211/linctl) {{.LinVersion}} on {{.Year}}

## Overview

{{.ProjectName | Title}} is a Go backend service built with the [miniblog-v4](https://github.com/clin211/miniblog-v4) project style.

## Tech Stack

- **Web Framework**: {{.Framework}}
- **Storage**: {{.Storage}}
- **Shared library**: [linhub](https://github.com/clin211/linhub) (`github.com/clin211/linhub`) — db, log, errx, core, store, options, etc.
- **Language**: Go {{.GoVersion}}

Local monorepo tip: `go.mod` includes `replace github.com/clin211/linhub => ../linhub` so the generated app builds next to your linhub checkout.

## Getting Started

```bash
# Install dependencies
make deps

# Build
make build

# Run
./_output/{{.AppName}} -c configs/{{.AppName}}.yaml
```

## Project Structure

```
{{.ProjectName}}/
├── cmd/{{.AppName}}/          # Application entry point
├── internal/{{.AppName}}/     # Internal application packages
│   ├── handler/               # HTTP handlers
│   ├── biz/                   # Business logic layer
│   └── store/                 # Data access layer
├── internal/pkg/              # Shared internal utilities
├── pkg/                       # Public packages
└── configs/                   # Configuration files
```

## Configuration

Edit `configs/{{.AppName}}.yaml` to configure the service.

## Author

{{.Author}} <{{.Email}}>
