{{- $app := (index .Project.Spec.Components 0).Name -}}
{{- $img := .Project.Spec.Defaults.Image -}}
# Code generated by linctl.
# Only allow adding new components.
# Modifying existing components or their configurations IS NOT ALLOWED.
# Delete PROJECT or rename PROJECT IS NOT ALLOWED.
scaffold: linctl
version: v0.1.0
metadata:
  modulePath: {{ .Project.Metadata.Module }}
  name: {{ .Project.Metadata.Name }}
  shortDescription: {{ .Project.Metadata.Description | default "Please update the short description of the binary file." }}
  longMessage: {{ .Project.Metadata.Description | default "Please update the detailed description of the binary file." }}
  image:
    registryPrefix: {{ $img.RegistryPrefix | default .Project.Metadata.Name }}
    dockerfileMode: {{ $img.DockerfileMode | default "multi-stage" }}
    distrolessMode: {{ $img.DistrolessMode | default "always" }}
  deploymentMethod: {{ .Project.Spec.Defaults.Deploy | default "docker" }}
  makefileMode: {{ .Project.Spec.Defaults.Makefile | default "unstructured" }}
  author: {{ .Project.Metadata.Author.Name | default "Please update the author name." }}
  email: {{ .Project.Metadata.Author.Email | default "noreply@example.com" }}
webServers:
{{- range .Project.Spec.Components }}
{{- if eq .Kind "WebServer" }}
- binaryName: {{ .Name }}
  webFramework: {{ .Framework | default "gin" }}
  storageType: {{ .Storage | default "memory" }}
  withHealthz: {{ if hasFeature .Features "healthz" }}true{{ else }}false{{ end }}
  withUser: {{ if hasFeature .Features "user" }}true{{ else }}false{{ end }}
  withOTel: true
  serviceRegistry: {{ .Registry | default "none" }}
{{- end }}
{{- end }}
