# {{.ProjectName | Title}} Documentation

> Generated by lin {{.LinVersion}}

## API Overview

The `{{.AppName}}` service exposes a RESTful API over HTTP.

### Base URL

```
http://localhost:8080/v1
```

### Endpoints

| Method | Path | Description |
|--------|------|-------------|
| GET | `/v1/healthz` | Service health check |

## Development Guide

See the project [README](../README.md) for setup and build instructions.
